sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t unchaptered/docker-dev-frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true unchaptered/docker-dev-frontend npm test

after_success:
  - docker build -t unchaptered/docker-app-frontend -f ./frontend/Dockerfile ./frontend
  - docker build -t unchaptered/docker-app-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t unchaptered/docker-app-backend -f ./backend/Dockerfile ./backend
  
  - docker login -u "$DOCKER_HUB_ID" -p "$DOCKER_ACCESS_TOKEN" docker.io

  - docker push unchaptered/docker-app-frontend
  - docker push unchaptered/docker-app-nginx
  - docker push unchaptered/docker-app-backend

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-proxy"
  env: "Dockerreactproxy-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-404540290465"
  bucket_pass: "docker-react-proxy"
  on:
    branch: main
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY