sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Create an image with Dockerfile"
  - docker build -t unchaptered/docker-dev-frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true unchaptered/docker-dev-frontend npm test

after_success:
  - docker build -t unchaptered/docker-app-frontend ./frontend
  - docker build -t unchaptered/docker-app-backend ./backend
  - docker build -t unchaptered/docker-app-nginx ./nginx
  
  - docker login -u "$DOCKER_HUB_ID" "$DOCKER_ACCESS_TOKEN"
  
  - docker push unchaptered/docker-app-frontend
  - docker push unchaptered/docker-app-backend
  - docker push unchaptered/docker-app-nginx