version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    container_name: app_frontend

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"
    restart: always
    container_name: app_nginx

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: app_backend
      
  # mysql:
  #   build: ./mysql
  #   ports:
  #     - "3307:3306"
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: reactpw
  #     MYSQL_DATABASE: reactapp
  #   container_name: app_mysql